#!/usr/bin/env bash
# comment-linkedin.sh — post (or update) the LinkedIn-ready plain text as a
# comment on the post PR opened by push-post.sh.
#
# Idempotent, matching push-post.sh's own idempotency: a re-run of the same
# source PR_NUMBER re-runs to-linkedin.py and pushes to the SAME branch/PR
# (push-post.sh reuses it rather than opening a duplicate), so this script
# must edit its own prior comment in place rather than posting a new one each
# time — otherwise a post that gets regenerated a few times would bury the
# post PR in stale copies of the text. The marker HTML comment
# (<!-- linkedin-text -->) as the first line of the comment body is how a
# prior run's comment is found again.
#
# Inputs (env):
#   POSTS_PAT     — PAT with pull-requests:write on TARGET_REPO (the default
#                   GITHUB_TOKEN is scoped to the CALLER repo and cannot
#                   comment on TARGET_REPO)
#   TARGET_REPO   — owner/name of the repo the post PR lives in
#   POST_PR_URL   — full URL of the post PR (from push-post.sh's pr_url output)
#   LINKEDIN_FILE — path to the converted plain-text file (to-linkedin.py's
#                   stdout, saved to disk)
#   STATS_LINE    — the one-line stats string to-linkedin.py printed to
#                   stderr (character counts + hook length)
set -euo pipefail

: "${POSTS_PAT:?POSTS_PAT env is required}"
: "${TARGET_REPO:?TARGET_REPO env is required}"
: "${POST_PR_URL:?POST_PR_URL env is required}"
: "${LINKEDIN_FILE:?LINKEDIN_FILE env is required}"

if [ ! -s "$LINKEDIN_FILE" ]; then
  echo "::error::LINKEDIN_FILE '${LINKEDIN_FILE}' is missing or empty."
  exit 1
fi

STATS_LINE="${STATS_LINE:-}"
MARKER="<!-- linkedin-text -->"

export GH_TOKEN="$POSTS_PAT"
export GH_HOST="github.com"

PR_NUMBER="$(basename "$POST_PR_URL")"

BODY_FILE="$(mktemp)"
trap 'rm -f "$BODY_FILE"' EXIT

{
  echo "$MARKER"
  echo "### 📋 LinkedIn-ready text"
  echo
  if [ -n "$STATS_LINE" ]; then
    echo "$STATS_LINE"
    echo
  fi
  echo '```text'
  cat "$LINKEDIN_FILE"
  echo '```'
  echo
  echo "<sub>Generated by <code>.github/scripts/to-linkedin.py</code>."
  echo "Use the copy button on the block above — it copies the plain-text bytes verbatim.</sub>"
} > "$BODY_FILE"

# Find a prior run's comment on THIS PR by its marker so a regeneration edits
# it in place instead of stacking a duplicate. --paginate handles PRs with
# more comments than fit one page; jq filters client-side since the REST API
# has no server-side "starts with" comment filter.
EXISTING_COMMENT_ID="$(gh api \
  "repos/${TARGET_REPO}/issues/${PR_NUMBER}/comments" \
  --paginate \
  --jq "[.[] | select(.body | startswith(\"${MARKER}\"))][0].id // empty" \
  2>/dev/null || true)"

if [ -n "$EXISTING_COMMENT_ID" ]; then
  echo "::notice::Updating existing LinkedIn-text comment ${EXISTING_COMMENT_ID} on ${POST_PR_URL}."
  # -F (not -f): gh's `@file` value-from-file magic is documented under
  # -F/--field, not -f/--raw-field — `-f body=@file` sends the LITERAL
  # string "@file" as the body, not the file's content (verified against
  # gh 2.87.3 / the POST /markdown endpoint).
  gh api \
    --method PATCH \
    "repos/${TARGET_REPO}/issues/comments/${EXISTING_COMMENT_ID}" \
    -F "body=@${BODY_FILE}" \
    > /dev/null
else
  echo "::notice::Posting new LinkedIn-text comment on ${POST_PR_URL}."
  gh pr comment "$POST_PR_URL" --repo "$TARGET_REPO" --body-file "$BODY_FILE"
fi
